# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - tags.html
  - categories.html
  - feed.xml
  - about.md

footer: Albert // <a href="https://albertgabe.github.io">Home page.</a>

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # true or false (default)

title: Albert // Blog.
description: Albert's dumb blog.
url: https://albertgabe.github.io

plugins:
  - jekyll-seo-tag
